# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://money.yandex.ru/to/410012076838296/100','https://connect.smartliving.ru/tasks/50.html'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
